name: Check code and build

on:
  push:
    branches:
      - "**"

jobs:
  check-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.4"
          channel: "stable"
          cache: true

      - run: flutter pub get

      - run: dart format --set-exit-if-changed .

      - run: flutter analyze .

      - run: flutter test

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  android-build:
    needs: [check-code, sonarcloud]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Write Mapbox SDK secret
        run: |
          mkdir ~/.gradle
          echo "SDK_REGISTRY_TOKEN=${{ secrets.MAPBOX_SDK_KEY }}" >> ~/.gradle/gradle.properties

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT

      - uses: actions/setup-java@v2
        with:
          java-version: "12.x"
          distribution: "zulu"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.4"
          channel: "stable"
          cache: true

      - run: flutter pub get

      - run: flutter build apk --dart-define PUBLIC_ACCESS_TOKEN=${{ secrets.PUBLIC_ACCESS_TOKEN }}

      - name: Store APK
        uses: actions/upload-artifact@v4
        with:
          name: field-companion.apk
          path: build/app/outputs/apk/release/app-release.apk

  ios-build:
    needs: [check-code, sonarcloud]

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Write Mapbox SDK secret
        run: | 
          echo "machine api.mapbox.com" >> ~/.netrc
          echo "login mapbox" >> ~/.netrc
          echo "password ${{ secrets.MAPBOX_SDK_KEY }}" >> ~/.netrc

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.4"
          channel: "stable"
          cache: true

      - run: flutter pub get

      - run: flutter build ios --release --no-codesign --dart-define PUBLIC_ACCESS_TOKEN=${{ secrets.PUBLIC_ACCESS_TOKEN }}

      - run: flutter test integration_test -d macOS

      - name: Store APK
        uses: actions/upload-artifact@v4
        with:
          name: field-companion.app
          path: build/ios/iphoneos/Runner.app
