name: check pull request

on:
  pull_request:
    branches:
      - 'main'

env:
  FLUTTER_VERSION: 3.22.2

jobs:
  check-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true

      - run: flutter pub get

      - run: dart format --set-exit-if-changed .

      - run: flutter analyze .

      - run: flutter test

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  android-build:
    needs: [check-code, sonarcloud]

    env:
      SDK_REGISTRY_TOKEN: ${{ secrets.SDK_REGISTRY_TOKEN }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "zulu"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true

      - run: flutter pub get

      - run: flutter build appbundle --release --build-name="Main build ${{ github.run_number }}" --build-number=${{ github.run_number }} --dart-define=PUBLIC_ACCESS_TOKEN=${{ secrets.PUBLIC_ACCESS_TOKEN }}

  ios-build:
    needs: [check-code, sonarcloud]

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Write Mapbox SDK secret
        run: | 
          echo "machine api.mapbox.com" >> ~/.netrc
          echo "  login mapbox" >> ~/.netrc
          echo "  password ${{ secrets.MAPBOX_SDK_KEY }}" >> ~/.netrc
          chmod 600 ~/.netrc

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true

      - run: flutter pub get

      - run: flutter build ios --release --no-codesign --dart-define PUBLIC_ACCESS_TOKEN=${{ secrets.PUBLIC_ACCESS_TOKEN }}
